language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2 # caching maven dependencies to speed up the build
install: true # skipping default install step
script: 
  - mvn test -Dlicense_key=$LICENSE_KEY -B
